export const ERROR_CODES = {
  VALIDATION_ERROR: 400,
  INVALID_QUERY_PARAMS: 400,
  ENTITY_RESOLUTION_FAILED: 422,
  ADAPTER_UPSTREAM_ERROR: 502,
  RATE_LIMIT_EXCEEDED: 429,
  RESOURCE_NOT_FOUND: 404,
  REPORT_GENERATION_FAILED: 500,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const ERROR_TYPES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_QUERY_PARAMS: "INVALID_QUERY_PARAMS",
  ENTITY_RESOLUTION_FAILED: "ENTITY_RESOLUTION_FAILED",
  ADAPTER_UPSTREAM_ERROR: "ADAPTER_UPSTREAM_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  REPORT_GENERATION_FAILED: "REPORT_GENERATION_FAILED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;
